// change this if you want to change the default list of topics
var topics = {
	'Agile'   : [
	    "Системное мышление",
        "Зачем Скраму Канбан?",
        "О доверии в командах",
        "MVP. You're getting it wrong",
        "Измерение индивидуальной производительности членов команды и скрам мастеров",
		"Agile Tools",
		"Agile",
		"Burndown Charts",
		"Continuous Delivery",
		"Continuous Improvement",
		"Daily Stand-up",
		"Failure",
		"Guilds, Tribes and Squads",
		"My worst agile experience",
		"Pair Programming",
		"Planning Poker",
		"Product Ownership",
		"Project Managers",
		"Retrospective",
		"Scaling Agile",
		"Scrum Masters",
		"Scrum",
		"Teams",
        "Test-Driven Development",
		"The last book you read",
		"This presentation",
		"Too much feedback",
		"Traffic in this city",
		"Training",
		"Velocity",
		"What it takes to be a Scrum Master",
	],
	'QA' : [
	    "Как обеспечить безопасность в онлайн-банке для ваших пользователей?",
        "QA. Good to great",
        "ТОП 10 ПРАНКОВ с performance тестами",
        "Serverless архитектура и её использование в автоматизации тестирования",
        "Как сократить QA team в 5 раз и уменьшить поток \"жалоб\" в 2 раза",
        "Невоспроизводимые баги",
        "Ловушки мышления в тестировании",
        "Тестовая стратегия",
        "A/B Testing",
        "Самый критичный баг в моей жизни",
        "Это не баг, это фича!",
        "The trickiest bug I found",
        "Performance Testing",
        "Load Testing",
        "Smoke Testing",
        "Blackbox Testing",
        "Automated Testing",
        "Regresion Testing",
        "Build quality in",
        "Testing",
        "What it takes to be a QA",
        "Microservices and how to test them",
        "Hardware testing automation",
        "Beta-testing",
        "Selenium",
        "BDD",
        "ATDD",
        "Як приборкати девелопера",
        "Risk Analysis",
        "Тестирование и котики",
    ],
    'Funny': [
        "Любимая, мы убиваем проект",
        "Я стесняюсь своего кода",
        "Меняю тим лида",
        "Кюейша в 16",
        "UX фактор",
        "Танцы с бубнами",
        "Мастер скрам",
        "Релизнутые и счастливые",
        "От пацанки до QA",
        "Тестируют все",
        "Тестируют все: дети",
        "Битва архитекторов",
        "Продебаженные и счастливые",
        "Как пахать поле по Scrum",
        "Блеск и нищета аутсорса",
    ]
};
